### ISSUE TITLE
Incorrect Readme reference

### ISSUE THREAD

**Issue by olafbond** [fkscott/workflowy-calendar-generator#11]
Hi.
I do like your project. I'm an amateur coder, trying to participate in WorkFlowy community.
Any way, feel free using ideas and my code: https://github.com/olafbond/WorkFlowy-calendar-script.
I've just added a habit tracker and some other stuff.
Your Readme says my code gives plain text dates. Actually not. I would appreciate if you'll fix the reference.
Thanks.

**Comment by fkscott** [comment]
My apologies. I'll correct the README
