### ISSUE TITLE
Option to add the year after the month in the month heading. 

### ISSUE THREAD

**Issue by kingsinger** [fkscott/workflowy-calendar-generator#3]
I tend to keep all of my months in a single running flat list with each month's heading as follows: [Month Name] [Year] (i.e., October 2024). Any way to add another option to have the generator generate the month heading with that formatting?

Thanks!

**Comment by fkscott** [comment]
@kingsinger Do you still keep all of your months under a root "Year" heading / node. For example Something like this:

- 2024
    - October 2024
    - November 2024

**Comment by kingsinger** [comment]
No, I don't keep it under a root heading node by year like that. I just
have all the years in one flat list. But I can see the virtue of having
both options.

**Comment by kingsinger** [comment]
Or to be clearer, I should have said, I just keep all the [Month] [Years] in one flat list like this:

- November 2024
- December 2024
- January 2025
- February 2025

**Comment by fkscott** [comment]
@kingsinger i just pushed an update for this. let me know if theres any issues and i can reopen this issue.

**Comment by kingsinger** [comment]
Seems to work as expected. Thanks!
