### ISSUE TITLE
No copyied text

### ISSUE THREAD

**Issue by dannebrob** [fkscott/workflowy-calendar-generator#8]
When creating a new calendar in Chrome, nothing is copied, just blank. This occurs when I choose a header (any combination) and also without.

**Comment by fkscott** [comment]
Open your browser console, when you click the button do you see any logging statements that say “copied to clipboard”?On Oct 24, 2024, at 2:33 AM, Daniel Brobäck ***@***.***> wrote:﻿
When creating a new calendar in Chrome, nothing is copied, just blank. This occurs when I choose a header (any combination) and also without.

**Comment by dannebrob** [comment]
Yes, that is correct. The console returns ”copied to clipboard” every time I click the button. But the clipboard object is blank.

Den 24 okt. 2024 kl 14:44, Keagan Scott ***@***.***(mailto:Den 24 okt. 2024 kl 14:44, Keagan Scott <<a href=)> skrev:

**Comment by fkscott** [comment]
That is strange. Maybe it is something to do with extensions? What version of Chrome? 

I've been able to copy text on iOS 18 Safari, and Windows Chrome 130.0.6723.59. Also have tested on macOS with Firefox and Chrome as well.

**Comment by dannebrob** [comment]
I’m sorry, this is a user error. I did not click ‘Generate’, therefore there was nothing to copy. Totally my fault.

**Comment by fkscott** [comment]
No worries. I can push a change to make the buttons a little more visible.

**Comment by dannebrob** [comment]
I have not looked at your code, but you could make a function that looks at the variable that holds the value of the generated calendar and make the copy button disabled if it’s false (holds no value). I really like your project otherwise. It’s really cool!
